version: '3.5'

volumes:
  pgdata:

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: opinio_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init/script.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
